type busDataType = {    
    monitoredVehicleJourneyBearing: number,
    monitoredVehicleJourneyDataSource: string,
    monitoredVehicleJourneyDelay: string,
    monitoredVehicleJourneyDestinationAimedArrivalTime: string,
    monitoredVehicleJourneyDestinationNameText: string, 
    monitoredVehicleJourneyDestinationNameXmlLang: string,
    monitoredVehicleJourneyDestinationRef: string, 
    monitoredVehicleJourneyFramedVehicleJourneyRefDataFrameRef: string,
    monitoredVehicleJourneyFramedVehicleJourneyRefDatedVehicleJourneyRef: string,
    monitoredVehicleJourneyIsCompleteStopSequence: boolean,
    monitoredVehicleJourneyLineRef: number, 
    monitoredVehicleJourneyMonitored: boolean, 
    monitoredVehicleJourneyMonitoredCallDestinationDisplay: string,
    monitoredVehicleJourneyMonitoredCallStopPointName: string, 
    monitoredVehicleJourneyMonitoredCallStopPointRef: string, 
    monitoredVehicleJourneyMonitoredCallVehicleLocationAtStopLatitude: number,
    monitoredVehicleJourneyMonitoredCallVehicleLocationAtStopLongitude:number,
    monitoredVehicleJourneyOperatorRef: number,
    monitoredVehicleJourneyOriginAimedDepartureTime: string,
    monitoredVehicleJourneyOriginNameText: string | null, 
    monitoredVehicleJourneyOriginNameXmlLang: string | null,
    monitoredVehicleJourneyOriginRef: string,
    monitoredVehicleJourneyVehicleLocationLatitude: number,
    monitoredVehicleJourneyVehicleLocationLongitude: number,
    monitoredVehicleJourneyVehicleMode: string,
    monitoredVehicleJourneyVehicleRef: number,
    //Enumerate
    monitoredVehicleJourneyVehicleStatus: string,
    monitoredVehicleJourneyVelocity: number,
    recordedAtTime: string,
    responseTimestamp: string,
    validUntilTime: string
}

export const busDataTypeString = `{
    monitoredVehicleJourneyDataSource: string,
    // The bearing is a the number of degrees from north. -90 is west, 0 is north, 90 is east and 180 is south. The number is never greater than 180.
    monitoredVehicleJourneyBearing: number,
    // The delay is in this format: PT3M46S
    monitoredVehicleJourneyDelay: string,
    monitoredVehicleJourneyDestinationAimedArrivalTime: string,
    monitoredVehicleJourneyDestinationNameText: string, 
    monitoredVehicleJourneyDestinationNameXmlLang: string,
    monitoredVehicleJourneyDestinationRef: string, 
    monitoredVehicleJourneyFramedVehicleJourneyRefDataFrameRef: string,
    monitoredVehicleJourneyFramedVehicleJourneyRefDatedVehicleJourneyRef: string,
    monitoredVehicleJourneyIsCompleteStopSequence: boolean,
    // Line reference is a number of type string
    monitoredVehicleJourneyLineRef: string, 
    monitoredVehicleJourneyMonitored: boolean, 
    monitoredVehicleJourneyMonitoredCallDestinationDisplay: string,
    monitoredVehicleJourneyMonitoredCallStopPointName: string, 
    monitoredVehicleJourneyMonitoredCallStopPointRef: string, 
    monitoredVehicleJourneyMonitoredCallVehicleLocationAtStopLatitude: number,
    monitoredVehicleJourneyMonitoredCallVehicleLocationAtStopLongitude:number,
    monitoredVehicleJourneyOperatorRef: number,
    monitoredVehicleJourneyOriginAimedDepartureTime: string,
    monitoredVehicleJourneyOriginNameText: string | null, 
    monitoredVehicleJourneyOriginNameXmlLang: string | null,
    monitoredVehicleJourneyOriginRef: string,
    monitoredVehicleJourneyVehicleLocationLatitude: number,
    monitoredVehicleJourneyVehicleLocationLongitude: number,
    monitoredVehicleJourneyVehicleMode: string,
    monitoredVehicleJourneyVehicleRef: number,
    monitoredVehicleJourneyVehicleStatus: string,
    // The velocity is in km/h
    monitoredVehicleJourneyVelocity: number,
    recordedAtTime: string,
    responseTimestamp: string,
    validUntilTime: string
}`
export default busDataType;